<?php

namespace AppBundle\Repository;

/**
 * ExpensePlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpensePlanRepository extends \Doctrine\ORM\EntityRepository
{
}
